#!bin/bash
source configStep
#bash IDFlakies.sh $BASEDIR $REPOFOLDER
bash firstStep.sh $CSVINPUTFIRSTSTEP $REPOFOLDER $BASEDIR $CSVOUTPUTFIRSTSTEP
bash secondStep.sh $CSVINPUTFIRSTSTEP $CSVOUTPUT $BASEDIR $REPOFOLDER  $NITER $NROUND $CSVOUTPUTFINAL $OUTPUTLOG $STATELOG
